owner: msieberer
repo: monitor
sites: 
  - name: Mailcow
    url: https://mail.sieberer.dev
assignees:
  - msieberer
#status-website: # Status website (optional)
#  cname: upptime.js.org # Custom domain CNAME
#  name: Upptime # Status website title
status-website:
  baseUrl: monitor
  name: Your Status Website
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
