owner: msieberer
repo: monitor
sites: 
  - name: Mailcow
    url: https://mail.sieberer.dev
  - name: Mailcow IMAP
    check: "tcp-ping"
    url: mail.sieberer.dev
    port: 993
  - name: Mailcow SMTP
    check: "tcp-ping"
    url: mail.sieberer.dev
    port: 587
assignees:
  - msieberer
#status-website: # Status website (optional)
#  cname: upptime.js.org # Custom domain CNAME
#  name: Upptime # Status website title
status-website:
  baseUrl: monitor
  name: Your Status Website
#skipDescriptionUpdate: true
#skipTopicsUpdate: true
#skipHomepageUpdate: true
