owner: msieberer
repo: monitor
sites: 
  - name: Mailcow
    url: https://mail.sieberer.dev
  - name: Mailcow IMAP
    check: "tcp-ping"
    url: mail.sieberer.dev
    port: 993
  - name: Mailcow SMTP
    check: "tcp-ping"
    url: mail.sieberer.dev
    port: 587
assignees:
  - msieberer
#status-website: # Status website (optional)
#  cname: upptime.js.org # Custom domain CNAME
#  name: Upptime # Status website title
status-website:
  baseUrl: monitor
  name: Your Status Website
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"  
#skipDescriptionUpdate: true
#skipTopicsUpdate: true
#skipHomepageUpdate: true
